-- MySQL Script generated by MySQL Workbench
-- Mon 05 Dec 2016 10:33:39 AM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema andamio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema andamio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `andamio` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `andamio` ;

-- -----------------------------------------------------
-- Table `andamio`.`tipousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andamio`.`tipousuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `andamio`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andamio`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `primerapellido` VARCHAR(255) NULL,
  `segundoapellido` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `login` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `id_tipousuario` INT NULL,
  `firma` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_tipousuario_idx` (`id_tipousuario` ASC),
  CONSTRAINT `fk_usuario_tipousuario`
    FOREIGN KEY (`id_tipousuario`)
    REFERENCES `andamio`.`tipousuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `andamio`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andamio`.`proyecto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `andamio`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andamio`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `andamio`.`prioridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andamio`.`prioridad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `andamio`.`valoracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andamio`.`valoracion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `andamio`.`tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andamio`.`tarea` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `alta` DATETIME NULL,
  `integracion` DATETIME NULL,
  `puntos` INT NULL,
  `observaciones` VARCHAR(255) NULL,
  `fechaturno` VARCHAR(255) NULL,
  `turno` INT NULL,
  `numeroturno` INT NULL,
  `id_usuario` INT NULL,
  `id_estado` INT NULL,
  `id_prioridad` INT NULL,
  `id_valoracion` INT NULL,
  `id_proyecto` INT NULL,
  `completada` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tarea_usuario1_idx` (`id_usuario` ASC),
  INDEX `fk_tarea_estado1_idx` (`id_estado` ASC),
  INDEX `fk_tarea_prioridad1_idx` (`id_prioridad` ASC),
  INDEX `fk_tarea_valoracion1_idx` (`id_valoracion` ASC),
  INDEX `fk_tarea_proyecto1_idx` (`id_proyecto` ASC),
  CONSTRAINT `fk_tarea_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `andamio`.`usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tarea_estado1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `andamio`.`estado` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tarea_prioridad1`
    FOREIGN KEY (`id_prioridad`)
    REFERENCES `andamio`.`prioridad` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tarea_valoracion1`
    FOREIGN KEY (`id_valoracion`)
    REFERENCES `andamio`.`valoracion` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tarea_proyecto1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `andamio`.`proyecto` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `andamio`.`titulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andamio`.`titulo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_titulo_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_titulo_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `andamio`.`usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `andamio`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andamio`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `titulo` VARCHAR(255) NULL,
  `contenido` LONGTEXT NULL,
  `id_titulo` INT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_titulo1_idx` (`id_titulo` ASC),
  INDEX `fk_post_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_post_titulo1`
    FOREIGN KEY (`id_titulo`)
    REFERENCES `andamio`.`titulo` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `andamio`.`usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `andamio`.`aviso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `andamio`.`aviso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenido` VARCHAR(255) NULL,
  `fecha` DATETIME NULL,
  `prioridad` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aviso_tipousuario1_idx` (`prioridad` ASC),
  CONSTRAINT `fk_aviso_tipousuario1`
    FOREIGN KEY (`prioridad`)
    REFERENCES `andamio`.`tipousuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



-- -----------------------------------------------------
-- -----------------------------------------------------
-- -----------------------------------------------------
-- -----------------------------------------------------
-- -----------------------------------------------------
-- -----------------------------------------------------





